# Generated by Django 4.0.4 on 2022-07-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_user_followers_alter_user_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
    ]
